# Generated by Django 4.1 on 2023-04-26 00:28

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_groups_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
