# Generated by Django 4.1 on 2023-04-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Not Choosen'), (1, 'Bachelor Degree'), (2, 'Master Degree'), (3, 'Graduated')], default=0),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not Choosen'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
