# Generated by Django 4.1 on 2023-06-06 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uclks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='amount_of_assignments',
            field=models.IntegerField(choices=[(1, 'Very Few'), (2, 'Few'), (3, 'Normal'), (4, 'Many'), (5, 'Very Many')], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='evaluation',
            field=models.IntegerField(choices=[(1, 'Very Very Shxt'), (2, 'Very Shxt'), (3, 'Shit'), (4, 'Below Average'), (5, 'Average'), (6, 'Good'), (7, 'Very Good'), (8, 'Excellent'), (9, 'Fxcking Amazing'), (10, 'Free First')], default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='exam_difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Difficult'), (5, 'Very Difficult')], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_compulsory',
            field=models.IntegerField(choices=[(0, 'Not Compulsory'), (1, 'Compulsory')], default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedbacks', to='uclks_api.modules'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='module_difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Difficult'), (5, 'Very Difficult')], default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modules',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
